version: '3'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8000"
    environment:
      DJANGO_ENV: "test"
    volumes:
      - ./backend:/app
    command: >
      python manage.py runserver 0.0.0.0:8000

  frontend:
    build:
      context: ./frontend
    ports:
      - "3001:3000"
    environment:
      NODE_ENV: "test"
    volumes:
      - ./frontend:/app
    command: [ "npm", "run", "dev" ]
    depends_on:
      - backend