# Generated by Django 5.1.1 on 2024-10-20 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersystem',
            name='zabbix_server_url',
            field=models.CharField(max_length=255),
        ),
    ]
