# Generated by Django 5.1.1 on 2024-10-30 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_alter_usersystem_zabbix_server_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('path', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('metrics', models.JSONField()),
            ],
        ),
        migrations.AddField(
            model_name='usersystem',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_users', to='settings.usersystem'),
        ),
        migrations.AddField(
            model_name='usersystem',
            name='user_type',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('user', 'User')], default='user', max_length=20),
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.apiendpoint')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='settings.usersystem')),
            ],
            options={
                'unique_together': {('user', 'endpoint')},
            },
        ),
    ]
