# Generated by Django 5.1.1 on 2024-11-06 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_alter_usersystem_zabbix_host_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersystem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
