# Generated by Django 5.1.1 on 2024-10-30 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_apiendpoint_usersystem_admin_usersystem_user_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersystem',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], default='user', max_length=20),
        ),
    ]
