# Generated by Django 5.1.1 on 2024-11-06 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_usersystem_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersystem',
            old_name='is_active',
            new_name='active',
        ),
    ]
