# Generated by Django 5.1.1 on 2024-11-06 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_rename_is_active_usersystem_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersystem',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subusers', to='settings.usersystem'),
        ),
    ]
