# Generated by Django 5.1.1 on 2024-10-30 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_alter_usersystem_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiendpoint',
            name='description',
        ),
        migrations.RemoveField(
            model_name='apiendpoint',
            name='metrics',
        ),
        migrations.AddField(
            model_name='apiendpoint',
            name='metric',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usersystem',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], default='user', max_length=20),
        ),
        migrations.AlterField(
            model_name='usersystem',
            name='zabbix_host_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='usersystem',
            name='zabbix_password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='usersystem',
            name='zabbix_username',
            field=models.CharField(max_length=255),
        ),
    ]
