# Generated by Django 5.1.1 on 2024-10-30 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_remove_apiendpoint_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiendpoint',
            name='method',
            field=models.SmallIntegerField(choices=[(0, 'GET'), (1, 'POST')], default=0),
            preserve_default=False,
        ),
    ]
