# Generated by Django 5.1.1 on 2024-11-20 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_alter_usersystem_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='usersystem',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='system_permissions', to='settings.permission'),
        ),
    ]
