# Generated by Django 5.1.1 on 2024-11-17 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_alter_usersystem_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersystem',
            name='user_type',
            field=models.CharField(choices=[('super-admin', 'SuperAdmin'), ('admin', 'Admin'), ('user', 'User')], default='user', max_length=20),
        ),
    ]
