# Generated by Django 5.1.1 on 2024-10-30 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_apiendpoint_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiendpoint',
            name='metric',
        ),
    ]
