# Generated by Django 5.1.1 on 2024-11-20 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_permission_usersystem_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='codename',
            field=models.CharField(default=None, max_length=5),
        ),
    ]
