# Generated by Django 5.1.1 on 2024-11-20 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0010_remove_permission_codename'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('codename', models.CharField(max_length=5, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
        migrations.AlterField(
            model_name='usersystem',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='system_permissions', to='settings.permissions'),
        ),
    ]
