# Generated by Django 5.1.1 on 2024-11-20 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0011_permissions_delete_permission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissions',
            name='codename',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
