# Generated by Django 5.1.1 on 2024-11-24 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_alter_usersystem_user_type'),
        ('settings', '0012_alter_permissions_codename'),
    ]

    operations = [
    ]
