# Generated by Django 5.1.1 on 2024-11-27 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0014_alter_usersystem_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersystem',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
