# Generated by Django 5.1.1 on 2024-12-17 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0015_usersystem_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersystem',
            name='email',
        ),
        migrations.AddField(
            model_name='usersystem',
            name='script_file',
            field=models.FileField(blank=True, null=True, upload_to='scripts'),
        ),
    ]
