# Generated by Django 5.1.1 on 2024-12-18 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0016_remove_usersystem_email_usersystem_script_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersystem',
            name='script_file',
            field=models.FileField(blank=True, null=True, upload_to='e8eb5dc92a5444888c1511942252ec46'),
        ),
    ]
