# Generated by Django 5.1.1 on 2024-11-24 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settings', '0014_alter_usersystem_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAlertPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_key', models.CharField(max_length=255)),
                ('enabled', models.BooleanField(default=False)),
                ('alert_level', models.CharField(choices=[('warning', 'Warning'), ('critical', 'Critical')], default='critical', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_preferences', to='settings.usersystem')),
            ],
            options={
                'unique_together': {('user', 'item_key')},
            },
        ),
    ]
